/*抵质押品router*/
import Vue from 'vue'
import Router from 'vue-router'
import agriculturalImplements from '@/views/securitymanagement/mortgagepledge/mpDetailForAgriculturalImplements'
import bill from '@/views/securitymanagement/mortgagepledge/mpDetailForBill'
import bond from '@/views/securitymanagement/mortgagepledge/mpDetailForBond'
import buildingProject from '@/views/securitymanagement/mortgagepledge/mpDetailForBuildingProject'
import chargeRight from '@/views/securitymanagement/mortgagepledge/mpDetailForChargeRight'
import depositReceipt from '@/views/securitymanagement/mortgagepledge/mpDetailForDepositReceipt'
import forestRight from '@/views/securitymanagement/mortgagepledge/mpDetailForForestRight'
import fund from '@/views/securitymanagement/mortgagepledge/mpDetailForFund'
import fundsOnAccount from '@/views/securitymanagement/mortgagepledge/mpDetailForFundsOnAccout'
import intellectualProjectRight from '@/views/securitymanagement/mortgagepledge/mpDetailForIntellectualPropertyRight'
import landManageRight from '@/views/securitymanagement/mortgagepledge/mpDetailForLandManageRight'
import landUseRight from '@/views/securitymanagement/mortgagepledge/mpDetailForLandUseRight'
import machineEquipment from '@/views/securitymanagement/mortgagepledge/mpDetailForMachineEquipment'
import motorVehicle from '@/views/securitymanagement/mortgagepledge/mpDetailForMotorVehicle'
import other from '@/views/securitymanagement/mortgagepledge/mpDetailForOther'
import otherMp from '@/views/securitymanagement/mortgagepledge/mpDetailForOtherMp'
import realty from '@/views/securitymanagement/mortgagepledge/mpDetailForRealty'
import salaryAccount from '@/views/securitymanagement/mortgagepledge/mpDetailForSalaryAccount'
import ship from '@/views/securitymanagement/mortgagepledge/mpDetailForShip'
import stock from '@/views/securitymanagement/mortgagepledge/mpDetailForStock'
import stockRight from '@/views/securitymanagement/mortgagepledge/mpDetailForStockRight'
import trafficTransportTool from '@/views/securitymanagement/mortgagepledge/mpDetailForTrafficTransportTool'
import wareHouseReceipt from '@/views/securitymanagement/mortgagepledge/mpDetailForWareHouseReceipt'
import warranty from '@/views/securitymanagement/mortgagepledge/mpDetailForWarranty'
import transferOwnership from '@/views/securitymanagement/mortgagepledge/mpTransferOwnership'
import notarizationInfo from '@/views/securitymanagement/mortgagepledge/mpNotarizationInfo'
import insuranceInfo from '@/views/securitymanagement/mortgagepledge/mpInsuranceInfo'
import checkInInfo from '@/views/securitymanagement/mortgagepledge/mpCheckInInfo'
import accidentInfo from '@/views/securitymanagement/mortgagepledge/mpAccidentInfo'
import summaryInfo from '@/views/securitymanagement/mortgagepledge/mpSummaryInfo'


