package com.cdgit.loan.user.bean;

import java.math.BigDecimal;
import java.util.Date;

public class tb_csm_corporation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.PARTY_ID
     *
     * @mbg.generated
     */
    private String partyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.CORP_CUSTOMER_TYPE_CD
     *
     * @mbg.generated
     */
    private String corpCustomerTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ENGLISH_NAME
     *
     * @mbg.generated
     */
    private String englishName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ECONOMIC_SECTOR_CODE
     *
     * @mbg.generated
     */
    private String economicSectorCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_CD
     *
     * @mbg.generated
     */
    private String industrialTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LISTING_CORPORATION
     *
     * @mbg.generated
     */
    private String listingCorporation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTER_ASSETS
     *
     * @mbg.generated
     */
    private BigDecimal registerAssets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTER_ASSETS_CURRENCY_CD
     *
     * @mbg.generated
     */
    private String registerAssetsCurrencyCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.EMPLOYEES_NUMBER
     *
     * @mbg.generated
     */
    private Long employeesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.GOVERNMENT_TENT_NO
     *
     * @mbg.generated
     */
    private String governmentTentNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.CREDIT_RELATIONSHIP_TIME
     *
     * @mbg.generated
     */
    private Date creditRelationshipTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTER_DATE
     *
     * @mbg.generated
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_NO
     *
     * @mbg.generated
     */
    private String legalCertificateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_END_DATE
     *
     * @mbg.generated
     */
    private Date legalCertificateEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTRATION_TYPE
     *
     * @mbg.generated
     */
    private String registrationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.UPDATE_USER_NUM
     *
     * @mbg.generated
     */
    private String updateUserNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.UPDATE_ORG_NUM
     *
     * @mbg.generated
     */
    private String updateOrgNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.AREA_TYPE
     *
     * @mbg.generated
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.CONTRY_REGION_CD
     *
     * @mbg.generated
     */
    private String contryRegionCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_NAME
     *
     * @mbg.generated
     */
    private String legalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_CERT_TYPE
     *
     * @mbg.generated
     */
    private String legalCertType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTR_CD
     *
     * @mbg.generated
     */
    private String registrCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.REGISTER_END_DATE
     *
     * @mbg.generated
     */
    private Date registerEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.BUSINESS_SCOPE
     *
     * @mbg.generated
     */
    private String businessScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ORG_REGISTER_CD
     *
     * @mbg.generated
     */
    private String orgRegisterCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ORG_REGISTER_END_DATE
     *
     * @mbg.generated
     */
    private Date orgRegisterEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.MIDDEL_CODE
     *
     * @mbg.generated
     */
    private String middelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ORG_CREDIT_CODE
     *
     * @mbg.generated
     */
    private String orgCreditCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.NATIONAL_TAX_NO
     *
     * @mbg.generated
     */
    private String nationalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_BIG_CD
     *
     * @mbg.generated
     */
    private String industrialTypeBigCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_MID_CD
     *
     * @mbg.generated
     */
    private String industrialTypeMidCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_SAMLL_CD
     *
     * @mbg.generated
     */
    private String industrialTypeSamllCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ENTERPRISE_SCALE_GX
     *
     * @mbg.generated
     */
    private String enterpriseScaleGx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.COUNT_BORE_ENTER_SCALE
     *
     * @mbg.generated
     */
    private String countBoreEnterScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.IS_GROUP_CUST
     *
     * @mbg.generated
     */
    private String isGroupCust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ATTACH_GROUP_NAME
     *
     * @mbg.generated
     */
    private String attachGroupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_IMP_EXP
     *
     * @mbg.generated
     */
    private String whetherImpExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.STOCKHOLDER_OF_BANK
     *
     * @mbg.generated
     */
    private String stockholderOfBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.JOINT_GUARANTEE
     *
     * @mbg.generated
     */
    private String jointGuarantee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.FAMILY_ENTERPRISE
     *
     * @mbg.generated
     */
    private String familyEnterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_GOVERNMENT_FINANCE_COR
     *
     * @mbg.generated
     */
    private String whetherGovernmentFinanceCor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.COUNTRYSIDE_ENTERPRISE
     *
     * @mbg.generated
     */
    private String countrysideEnterprise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_BLACK_LIST
     *
     * @mbg.generated
     */
    private String whetherBlackList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.FOCUS_CUSTOMER
     *
     * @mbg.generated
     */
    private String focusCustomer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.IS_REAL_ESTATE_DEV
     *
     * @mbg.generated
     */
    private String isRealEstateDev;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.CREATETIME
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.FUND_SRC
     *
     * @mbg.generated
     */
    private String fundSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.OPEN_FUND
     *
     * @mbg.generated
     */
    private BigDecimal openFund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.IS_BASEBANK_RELA_CUST
     *
     * @mbg.generated
     */
    private String isBasebankRelaCust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.THIRD_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    private String thirdCustTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.IS_THIRD_CUST
     *
     * @mbg.generated
     */
    private String isThirdCust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_END_DATE
     *
     * @mbg.generated
     */
    private Date enterpriseCertEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_NUM
     *
     * @mbg.generated
     */
    private String enterpriseCertNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.UNIFY_SOCIETY_CREDIT_NUM
     *
     * @mbg.generated
     */
    private String unifySocietyCreditNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.SINGLE_LP_CUST_IND
     *
     * @mbg.generated
     */
    private String singleLpCustInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.STOP_CORP_IND
     *
     * @mbg.generated
     */
    private String stopCorpInd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_CONTRY
     *
     * @mbg.generated
     */
    private String legalContry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.BANK_SCALE_IDENTIFY
     *
     * @mbg.generated
     */
    private String bankScaleIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_PHONE_NUMBER
     *
     * @mbg.generated
     */
    private String legalPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_REGIST_DATE
     *
     * @mbg.generated
     */
    private Date legalRegistDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LEGAL_CONTRY_SIGN
     *
     * @mbg.generated
     */
    private String legalContrySign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_TECHNIC
     *
     * @mbg.generated
     */
    private String whetherTechnic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_GREEN_GROUP
     *
     * @mbg.generated
     */
    private String whetherGreenGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_JMRH
     *
     * @mbg.generated
     */
    private String whetherJmrh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_ARG_RELATED
     *
     * @mbg.generated
     */
    private String whetherArgRelated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_OPEN_ACCT
     *
     * @mbg.generated
     */
    private String whetherOpenAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.WHETHER_POVERTY_ADD
     *
     * @mbg.generated
     */
    private String whetherPovertyAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.AREA
     *
     * @mbg.generated
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.OWNER
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.NATIONAL_ECONOMY_TYPE
     *
     * @mbg.generated
     */
    private String nationalEconomyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.CHAIN_SIGN
     *
     * @mbg.generated
     */
    private String chainSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.MAIN_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    private String mainCustTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.ORG_STATUS
     *
     * @mbg.generated
     */
    private String orgStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.IF_CSY
     *
     * @mbg.generated
     */
    private String ifCsy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_CSM_CORPORATION.LOAN_TURN
     *
     * @mbg.generated
     */
    private String loanTurn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.PARTY_ID
     *
     * @return the value of TB_CSM_CORPORATION.PARTY_ID
     *
     * @mbg.generated
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.PARTY_ID
     *
     * @param partyId the value for TB_CSM_CORPORATION.PARTY_ID
     *
     * @mbg.generated
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId == null ? null : partyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.CORP_CUSTOMER_TYPE_CD
     *
     * @return the value of TB_CSM_CORPORATION.CORP_CUSTOMER_TYPE_CD
     *
     * @mbg.generated
     */
    public String getCorpCustomerTypeCd() {
        return corpCustomerTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.CORP_CUSTOMER_TYPE_CD
     *
     * @param corpCustomerTypeCd the value for TB_CSM_CORPORATION.CORP_CUSTOMER_TYPE_CD
     *
     * @mbg.generated
     */
    public void setCorpCustomerTypeCd(String corpCustomerTypeCd) {
        this.corpCustomerTypeCd = corpCustomerTypeCd == null ? null : corpCustomerTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ENGLISH_NAME
     *
     * @return the value of TB_CSM_CORPORATION.ENGLISH_NAME
     *
     * @mbg.generated
     */
    public String getEnglishName() {
        return englishName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ENGLISH_NAME
     *
     * @param englishName the value for TB_CSM_CORPORATION.ENGLISH_NAME
     *
     * @mbg.generated
     */
    public void setEnglishName(String englishName) {
        this.englishName = englishName == null ? null : englishName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ECONOMIC_SECTOR_CODE
     *
     * @return the value of TB_CSM_CORPORATION.ECONOMIC_SECTOR_CODE
     *
     * @mbg.generated
     */
    public String getEconomicSectorCode() {
        return economicSectorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ECONOMIC_SECTOR_CODE
     *
     * @param economicSectorCode the value for TB_CSM_CORPORATION.ECONOMIC_SECTOR_CODE
     *
     * @mbg.generated
     */
    public void setEconomicSectorCode(String economicSectorCode) {
        this.economicSectorCode = economicSectorCode == null ? null : economicSectorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_CD
     *
     * @return the value of TB_CSM_CORPORATION.INDUSTRIAL_TYPE_CD
     *
     * @mbg.generated
     */
    public String getIndustrialTypeCd() {
        return industrialTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_CD
     *
     * @param industrialTypeCd the value for TB_CSM_CORPORATION.INDUSTRIAL_TYPE_CD
     *
     * @mbg.generated
     */
    public void setIndustrialTypeCd(String industrialTypeCd) {
        this.industrialTypeCd = industrialTypeCd == null ? null : industrialTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LISTING_CORPORATION
     *
     * @return the value of TB_CSM_CORPORATION.LISTING_CORPORATION
     *
     * @mbg.generated
     */
    public String getListingCorporation() {
        return listingCorporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LISTING_CORPORATION
     *
     * @param listingCorporation the value for TB_CSM_CORPORATION.LISTING_CORPORATION
     *
     * @mbg.generated
     */
    public void setListingCorporation(String listingCorporation) {
        this.listingCorporation = listingCorporation == null ? null : listingCorporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTER_ASSETS
     *
     * @return the value of TB_CSM_CORPORATION.REGISTER_ASSETS
     *
     * @mbg.generated
     */
    public BigDecimal getRegisterAssets() {
        return registerAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTER_ASSETS
     *
     * @param registerAssets the value for TB_CSM_CORPORATION.REGISTER_ASSETS
     *
     * @mbg.generated
     */
    public void setRegisterAssets(BigDecimal registerAssets) {
        this.registerAssets = registerAssets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTER_ASSETS_CURRENCY_CD
     *
     * @return the value of TB_CSM_CORPORATION.REGISTER_ASSETS_CURRENCY_CD
     *
     * @mbg.generated
     */
    public String getRegisterAssetsCurrencyCd() {
        return registerAssetsCurrencyCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTER_ASSETS_CURRENCY_CD
     *
     * @param registerAssetsCurrencyCd the value for TB_CSM_CORPORATION.REGISTER_ASSETS_CURRENCY_CD
     *
     * @mbg.generated
     */
    public void setRegisterAssetsCurrencyCd(String registerAssetsCurrencyCd) {
        this.registerAssetsCurrencyCd = registerAssetsCurrencyCd == null ? null : registerAssetsCurrencyCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.EMPLOYEES_NUMBER
     *
     * @return the value of TB_CSM_CORPORATION.EMPLOYEES_NUMBER
     *
     * @mbg.generated
     */
    public Long getEmployeesNumber() {
        return employeesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.EMPLOYEES_NUMBER
     *
     * @param employeesNumber the value for TB_CSM_CORPORATION.EMPLOYEES_NUMBER
     *
     * @mbg.generated
     */
    public void setEmployeesNumber(Long employeesNumber) {
        this.employeesNumber = employeesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.GOVERNMENT_TENT_NO
     *
     * @return the value of TB_CSM_CORPORATION.GOVERNMENT_TENT_NO
     *
     * @mbg.generated
     */
    public String getGovernmentTentNo() {
        return governmentTentNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.GOVERNMENT_TENT_NO
     *
     * @param governmentTentNo the value for TB_CSM_CORPORATION.GOVERNMENT_TENT_NO
     *
     * @mbg.generated
     */
    public void setGovernmentTentNo(String governmentTentNo) {
        this.governmentTentNo = governmentTentNo == null ? null : governmentTentNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.CREDIT_RELATIONSHIP_TIME
     *
     * @return the value of TB_CSM_CORPORATION.CREDIT_RELATIONSHIP_TIME
     *
     * @mbg.generated
     */
    public Date getCreditRelationshipTime() {
        return creditRelationshipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.CREDIT_RELATIONSHIP_TIME
     *
     * @param creditRelationshipTime the value for TB_CSM_CORPORATION.CREDIT_RELATIONSHIP_TIME
     *
     * @mbg.generated
     */
    public void setCreditRelationshipTime(Date creditRelationshipTime) {
        this.creditRelationshipTime = creditRelationshipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTER_DATE
     *
     * @return the value of TB_CSM_CORPORATION.REGISTER_DATE
     *
     * @mbg.generated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTER_DATE
     *
     * @param registerDate the value for TB_CSM_CORPORATION.REGISTER_DATE
     *
     * @mbg.generated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_NO
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_CERTIFICATE_NO
     *
     * @mbg.generated
     */
    public String getLegalCertificateNo() {
        return legalCertificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_NO
     *
     * @param legalCertificateNo the value for TB_CSM_CORPORATION.LEGAL_CERTIFICATE_NO
     *
     * @mbg.generated
     */
    public void setLegalCertificateNo(String legalCertificateNo) {
        this.legalCertificateNo = legalCertificateNo == null ? null : legalCertificateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_END_DATE
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_CERTIFICATE_END_DATE
     *
     * @mbg.generated
     */
    public Date getLegalCertificateEndDate() {
        return legalCertificateEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_CERTIFICATE_END_DATE
     *
     * @param legalCertificateEndDate the value for TB_CSM_CORPORATION.LEGAL_CERTIFICATE_END_DATE
     *
     * @mbg.generated
     */
    public void setLegalCertificateEndDate(Date legalCertificateEndDate) {
        this.legalCertificateEndDate = legalCertificateEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTRATION_TYPE
     *
     * @return the value of TB_CSM_CORPORATION.REGISTRATION_TYPE
     *
     * @mbg.generated
     */
    public String getRegistrationType() {
        return registrationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTRATION_TYPE
     *
     * @param registrationType the value for TB_CSM_CORPORATION.REGISTRATION_TYPE
     *
     * @mbg.generated
     */
    public void setRegistrationType(String registrationType) {
        this.registrationType = registrationType == null ? null : registrationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.UPDATE_USER_NUM
     *
     * @return the value of TB_CSM_CORPORATION.UPDATE_USER_NUM
     *
     * @mbg.generated
     */
    public String getUpdateUserNum() {
        return updateUserNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.UPDATE_USER_NUM
     *
     * @param updateUserNum the value for TB_CSM_CORPORATION.UPDATE_USER_NUM
     *
     * @mbg.generated
     */
    public void setUpdateUserNum(String updateUserNum) {
        this.updateUserNum = updateUserNum == null ? null : updateUserNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.UPDATE_ORG_NUM
     *
     * @return the value of TB_CSM_CORPORATION.UPDATE_ORG_NUM
     *
     * @mbg.generated
     */
    public String getUpdateOrgNum() {
        return updateOrgNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.UPDATE_ORG_NUM
     *
     * @param updateOrgNum the value for TB_CSM_CORPORATION.UPDATE_ORG_NUM
     *
     * @mbg.generated
     */
    public void setUpdateOrgNum(String updateOrgNum) {
        this.updateOrgNum = updateOrgNum == null ? null : updateOrgNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.UPDATE_TIME
     *
     * @return the value of TB_CSM_CORPORATION.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.UPDATE_TIME
     *
     * @param updateTime the value for TB_CSM_CORPORATION.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.AREA_TYPE
     *
     * @return the value of TB_CSM_CORPORATION.AREA_TYPE
     *
     * @mbg.generated
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.AREA_TYPE
     *
     * @param areaType the value for TB_CSM_CORPORATION.AREA_TYPE
     *
     * @mbg.generated
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.CONTRY_REGION_CD
     *
     * @return the value of TB_CSM_CORPORATION.CONTRY_REGION_CD
     *
     * @mbg.generated
     */
    public String getContryRegionCd() {
        return contryRegionCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.CONTRY_REGION_CD
     *
     * @param contryRegionCd the value for TB_CSM_CORPORATION.CONTRY_REGION_CD
     *
     * @mbg.generated
     */
    public void setContryRegionCd(String contryRegionCd) {
        this.contryRegionCd = contryRegionCd == null ? null : contryRegionCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_NAME
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_NAME
     *
     * @mbg.generated
     */
    public String getLegalName() {
        return legalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_NAME
     *
     * @param legalName the value for TB_CSM_CORPORATION.LEGAL_NAME
     *
     * @mbg.generated
     */
    public void setLegalName(String legalName) {
        this.legalName = legalName == null ? null : legalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_CERT_TYPE
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_CERT_TYPE
     *
     * @mbg.generated
     */
    public String getLegalCertType() {
        return legalCertType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_CERT_TYPE
     *
     * @param legalCertType the value for TB_CSM_CORPORATION.LEGAL_CERT_TYPE
     *
     * @mbg.generated
     */
    public void setLegalCertType(String legalCertType) {
        this.legalCertType = legalCertType == null ? null : legalCertType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTR_CD
     *
     * @return the value of TB_CSM_CORPORATION.REGISTR_CD
     *
     * @mbg.generated
     */
    public String getRegistrCd() {
        return registrCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTR_CD
     *
     * @param registrCd the value for TB_CSM_CORPORATION.REGISTR_CD
     *
     * @mbg.generated
     */
    public void setRegistrCd(String registrCd) {
        this.registrCd = registrCd == null ? null : registrCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.REGISTER_END_DATE
     *
     * @return the value of TB_CSM_CORPORATION.REGISTER_END_DATE
     *
     * @mbg.generated
     */
    public Date getRegisterEndDate() {
        return registerEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.REGISTER_END_DATE
     *
     * @param registerEndDate the value for TB_CSM_CORPORATION.REGISTER_END_DATE
     *
     * @mbg.generated
     */
    public void setRegisterEndDate(Date registerEndDate) {
        this.registerEndDate = registerEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.BUSINESS_SCOPE
     *
     * @return the value of TB_CSM_CORPORATION.BUSINESS_SCOPE
     *
     * @mbg.generated
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.BUSINESS_SCOPE
     *
     * @param businessScope the value for TB_CSM_CORPORATION.BUSINESS_SCOPE
     *
     * @mbg.generated
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ORG_REGISTER_CD
     *
     * @return the value of TB_CSM_CORPORATION.ORG_REGISTER_CD
     *
     * @mbg.generated
     */
    public String getOrgRegisterCd() {
        return orgRegisterCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ORG_REGISTER_CD
     *
     * @param orgRegisterCd the value for TB_CSM_CORPORATION.ORG_REGISTER_CD
     *
     * @mbg.generated
     */
    public void setOrgRegisterCd(String orgRegisterCd) {
        this.orgRegisterCd = orgRegisterCd == null ? null : orgRegisterCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ORG_REGISTER_END_DATE
     *
     * @return the value of TB_CSM_CORPORATION.ORG_REGISTER_END_DATE
     *
     * @mbg.generated
     */
    public Date getOrgRegisterEndDate() {
        return orgRegisterEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ORG_REGISTER_END_DATE
     *
     * @param orgRegisterEndDate the value for TB_CSM_CORPORATION.ORG_REGISTER_END_DATE
     *
     * @mbg.generated
     */
    public void setOrgRegisterEndDate(Date orgRegisterEndDate) {
        this.orgRegisterEndDate = orgRegisterEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.MIDDEL_CODE
     *
     * @return the value of TB_CSM_CORPORATION.MIDDEL_CODE
     *
     * @mbg.generated
     */
    public String getMiddelCode() {
        return middelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.MIDDEL_CODE
     *
     * @param middelCode the value for TB_CSM_CORPORATION.MIDDEL_CODE
     *
     * @mbg.generated
     */
    public void setMiddelCode(String middelCode) {
        this.middelCode = middelCode == null ? null : middelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ORG_CREDIT_CODE
     *
     * @return the value of TB_CSM_CORPORATION.ORG_CREDIT_CODE
     *
     * @mbg.generated
     */
    public String getOrgCreditCode() {
        return orgCreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ORG_CREDIT_CODE
     *
     * @param orgCreditCode the value for TB_CSM_CORPORATION.ORG_CREDIT_CODE
     *
     * @mbg.generated
     */
    public void setOrgCreditCode(String orgCreditCode) {
        this.orgCreditCode = orgCreditCode == null ? null : orgCreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.NATIONAL_TAX_NO
     *
     * @return the value of TB_CSM_CORPORATION.NATIONAL_TAX_NO
     *
     * @mbg.generated
     */
    public String getNationalTaxNo() {
        return nationalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.NATIONAL_TAX_NO
     *
     * @param nationalTaxNo the value for TB_CSM_CORPORATION.NATIONAL_TAX_NO
     *
     * @mbg.generated
     */
    public void setNationalTaxNo(String nationalTaxNo) {
        this.nationalTaxNo = nationalTaxNo == null ? null : nationalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_BIG_CD
     *
     * @return the value of TB_CSM_CORPORATION.INDUSTRIAL_TYPE_BIG_CD
     *
     * @mbg.generated
     */
    public String getIndustrialTypeBigCd() {
        return industrialTypeBigCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_BIG_CD
     *
     * @param industrialTypeBigCd the value for TB_CSM_CORPORATION.INDUSTRIAL_TYPE_BIG_CD
     *
     * @mbg.generated
     */
    public void setIndustrialTypeBigCd(String industrialTypeBigCd) {
        this.industrialTypeBigCd = industrialTypeBigCd == null ? null : industrialTypeBigCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_MID_CD
     *
     * @return the value of TB_CSM_CORPORATION.INDUSTRIAL_TYPE_MID_CD
     *
     * @mbg.generated
     */
    public String getIndustrialTypeMidCd() {
        return industrialTypeMidCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_MID_CD
     *
     * @param industrialTypeMidCd the value for TB_CSM_CORPORATION.INDUSTRIAL_TYPE_MID_CD
     *
     * @mbg.generated
     */
    public void setIndustrialTypeMidCd(String industrialTypeMidCd) {
        this.industrialTypeMidCd = industrialTypeMidCd == null ? null : industrialTypeMidCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_SAMLL_CD
     *
     * @return the value of TB_CSM_CORPORATION.INDUSTRIAL_TYPE_SAMLL_CD
     *
     * @mbg.generated
     */
    public String getIndustrialTypeSamllCd() {
        return industrialTypeSamllCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.INDUSTRIAL_TYPE_SAMLL_CD
     *
     * @param industrialTypeSamllCd the value for TB_CSM_CORPORATION.INDUSTRIAL_TYPE_SAMLL_CD
     *
     * @mbg.generated
     */
    public void setIndustrialTypeSamllCd(String industrialTypeSamllCd) {
        this.industrialTypeSamllCd = industrialTypeSamllCd == null ? null : industrialTypeSamllCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ENTERPRISE_SCALE_GX
     *
     * @return the value of TB_CSM_CORPORATION.ENTERPRISE_SCALE_GX
     *
     * @mbg.generated
     */
    public String getEnterpriseScaleGx() {
        return enterpriseScaleGx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ENTERPRISE_SCALE_GX
     *
     * @param enterpriseScaleGx the value for TB_CSM_CORPORATION.ENTERPRISE_SCALE_GX
     *
     * @mbg.generated
     */
    public void setEnterpriseScaleGx(String enterpriseScaleGx) {
        this.enterpriseScaleGx = enterpriseScaleGx == null ? null : enterpriseScaleGx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.COUNT_BORE_ENTER_SCALE
     *
     * @return the value of TB_CSM_CORPORATION.COUNT_BORE_ENTER_SCALE
     *
     * @mbg.generated
     */
    public String getCountBoreEnterScale() {
        return countBoreEnterScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.COUNT_BORE_ENTER_SCALE
     *
     * @param countBoreEnterScale the value for TB_CSM_CORPORATION.COUNT_BORE_ENTER_SCALE
     *
     * @mbg.generated
     */
    public void setCountBoreEnterScale(String countBoreEnterScale) {
        this.countBoreEnterScale = countBoreEnterScale == null ? null : countBoreEnterScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.IS_GROUP_CUST
     *
     * @return the value of TB_CSM_CORPORATION.IS_GROUP_CUST
     *
     * @mbg.generated
     */
    public String getIsGroupCust() {
        return isGroupCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.IS_GROUP_CUST
     *
     * @param isGroupCust the value for TB_CSM_CORPORATION.IS_GROUP_CUST
     *
     * @mbg.generated
     */
    public void setIsGroupCust(String isGroupCust) {
        this.isGroupCust = isGroupCust == null ? null : isGroupCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ATTACH_GROUP_NAME
     *
     * @return the value of TB_CSM_CORPORATION.ATTACH_GROUP_NAME
     *
     * @mbg.generated
     */
    public String getAttachGroupName() {
        return attachGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ATTACH_GROUP_NAME
     *
     * @param attachGroupName the value for TB_CSM_CORPORATION.ATTACH_GROUP_NAME
     *
     * @mbg.generated
     */
    public void setAttachGroupName(String attachGroupName) {
        this.attachGroupName = attachGroupName == null ? null : attachGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_IMP_EXP
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_IMP_EXP
     *
     * @mbg.generated
     */
    public String getWhetherImpExp() {
        return whetherImpExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_IMP_EXP
     *
     * @param whetherImpExp the value for TB_CSM_CORPORATION.WHETHER_IMP_EXP
     *
     * @mbg.generated
     */
    public void setWhetherImpExp(String whetherImpExp) {
        this.whetherImpExp = whetherImpExp == null ? null : whetherImpExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.STOCKHOLDER_OF_BANK
     *
     * @return the value of TB_CSM_CORPORATION.STOCKHOLDER_OF_BANK
     *
     * @mbg.generated
     */
    public String getStockholderOfBank() {
        return stockholderOfBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.STOCKHOLDER_OF_BANK
     *
     * @param stockholderOfBank the value for TB_CSM_CORPORATION.STOCKHOLDER_OF_BANK
     *
     * @mbg.generated
     */
    public void setStockholderOfBank(String stockholderOfBank) {
        this.stockholderOfBank = stockholderOfBank == null ? null : stockholderOfBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.JOINT_GUARANTEE
     *
     * @return the value of TB_CSM_CORPORATION.JOINT_GUARANTEE
     *
     * @mbg.generated
     */
    public String getJointGuarantee() {
        return jointGuarantee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.JOINT_GUARANTEE
     *
     * @param jointGuarantee the value for TB_CSM_CORPORATION.JOINT_GUARANTEE
     *
     * @mbg.generated
     */
    public void setJointGuarantee(String jointGuarantee) {
        this.jointGuarantee = jointGuarantee == null ? null : jointGuarantee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.FAMILY_ENTERPRISE
     *
     * @return the value of TB_CSM_CORPORATION.FAMILY_ENTERPRISE
     *
     * @mbg.generated
     */
    public String getFamilyEnterprise() {
        return familyEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.FAMILY_ENTERPRISE
     *
     * @param familyEnterprise the value for TB_CSM_CORPORATION.FAMILY_ENTERPRISE
     *
     * @mbg.generated
     */
    public void setFamilyEnterprise(String familyEnterprise) {
        this.familyEnterprise = familyEnterprise == null ? null : familyEnterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_GOVERNMENT_FINANCE_COR
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_GOVERNMENT_FINANCE_COR
     *
     * @mbg.generated
     */
    public String getWhetherGovernmentFinanceCor() {
        return whetherGovernmentFinanceCor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_GOVERNMENT_FINANCE_COR
     *
     * @param whetherGovernmentFinanceCor the value for TB_CSM_CORPORATION.WHETHER_GOVERNMENT_FINANCE_COR
     *
     * @mbg.generated
     */
    public void setWhetherGovernmentFinanceCor(String whetherGovernmentFinanceCor) {
        this.whetherGovernmentFinanceCor = whetherGovernmentFinanceCor == null ? null : whetherGovernmentFinanceCor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.COUNTRYSIDE_ENTERPRISE
     *
     * @return the value of TB_CSM_CORPORATION.COUNTRYSIDE_ENTERPRISE
     *
     * @mbg.generated
     */
    public String getCountrysideEnterprise() {
        return countrysideEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.COUNTRYSIDE_ENTERPRISE
     *
     * @param countrysideEnterprise the value for TB_CSM_CORPORATION.COUNTRYSIDE_ENTERPRISE
     *
     * @mbg.generated
     */
    public void setCountrysideEnterprise(String countrysideEnterprise) {
        this.countrysideEnterprise = countrysideEnterprise == null ? null : countrysideEnterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_BLACK_LIST
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_BLACK_LIST
     *
     * @mbg.generated
     */
    public String getWhetherBlackList() {
        return whetherBlackList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_BLACK_LIST
     *
     * @param whetherBlackList the value for TB_CSM_CORPORATION.WHETHER_BLACK_LIST
     *
     * @mbg.generated
     */
    public void setWhetherBlackList(String whetherBlackList) {
        this.whetherBlackList = whetherBlackList == null ? null : whetherBlackList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.FOCUS_CUSTOMER
     *
     * @return the value of TB_CSM_CORPORATION.FOCUS_CUSTOMER
     *
     * @mbg.generated
     */
    public String getFocusCustomer() {
        return focusCustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.FOCUS_CUSTOMER
     *
     * @param focusCustomer the value for TB_CSM_CORPORATION.FOCUS_CUSTOMER
     *
     * @mbg.generated
     */
    public void setFocusCustomer(String focusCustomer) {
        this.focusCustomer = focusCustomer == null ? null : focusCustomer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.IS_REAL_ESTATE_DEV
     *
     * @return the value of TB_CSM_CORPORATION.IS_REAL_ESTATE_DEV
     *
     * @mbg.generated
     */
    public String getIsRealEstateDev() {
        return isRealEstateDev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.IS_REAL_ESTATE_DEV
     *
     * @param isRealEstateDev the value for TB_CSM_CORPORATION.IS_REAL_ESTATE_DEV
     *
     * @mbg.generated
     */
    public void setIsRealEstateDev(String isRealEstateDev) {
        this.isRealEstateDev = isRealEstateDev == null ? null : isRealEstateDev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.CREATETIME
     *
     * @return the value of TB_CSM_CORPORATION.CREATETIME
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.CREATETIME
     *
     * @param createtime the value for TB_CSM_CORPORATION.CREATETIME
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.FUND_SRC
     *
     * @return the value of TB_CSM_CORPORATION.FUND_SRC
     *
     * @mbg.generated
     */
    public String getFundSrc() {
        return fundSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.FUND_SRC
     *
     * @param fundSrc the value for TB_CSM_CORPORATION.FUND_SRC
     *
     * @mbg.generated
     */
    public void setFundSrc(String fundSrc) {
        this.fundSrc = fundSrc == null ? null : fundSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.OPEN_FUND
     *
     * @return the value of TB_CSM_CORPORATION.OPEN_FUND
     *
     * @mbg.generated
     */
    public BigDecimal getOpenFund() {
        return openFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.OPEN_FUND
     *
     * @param openFund the value for TB_CSM_CORPORATION.OPEN_FUND
     *
     * @mbg.generated
     */
    public void setOpenFund(BigDecimal openFund) {
        this.openFund = openFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.IS_BASEBANK_RELA_CUST
     *
     * @return the value of TB_CSM_CORPORATION.IS_BASEBANK_RELA_CUST
     *
     * @mbg.generated
     */
    public String getIsBasebankRelaCust() {
        return isBasebankRelaCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.IS_BASEBANK_RELA_CUST
     *
     * @param isBasebankRelaCust the value for TB_CSM_CORPORATION.IS_BASEBANK_RELA_CUST
     *
     * @mbg.generated
     */
    public void setIsBasebankRelaCust(String isBasebankRelaCust) {
        this.isBasebankRelaCust = isBasebankRelaCust == null ? null : isBasebankRelaCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.THIRD_CUST_TYPE_CD
     *
     * @return the value of TB_CSM_CORPORATION.THIRD_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public String getThirdCustTypeCd() {
        return thirdCustTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.THIRD_CUST_TYPE_CD
     *
     * @param thirdCustTypeCd the value for TB_CSM_CORPORATION.THIRD_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public void setThirdCustTypeCd(String thirdCustTypeCd) {
        this.thirdCustTypeCd = thirdCustTypeCd == null ? null : thirdCustTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.IS_THIRD_CUST
     *
     * @return the value of TB_CSM_CORPORATION.IS_THIRD_CUST
     *
     * @mbg.generated
     */
    public String getIsThirdCust() {
        return isThirdCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.IS_THIRD_CUST
     *
     * @param isThirdCust the value for TB_CSM_CORPORATION.IS_THIRD_CUST
     *
     * @mbg.generated
     */
    public void setIsThirdCust(String isThirdCust) {
        this.isThirdCust = isThirdCust == null ? null : isThirdCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_END_DATE
     *
     * @return the value of TB_CSM_CORPORATION.ENTERPRISE_CERT_END_DATE
     *
     * @mbg.generated
     */
    public Date getEnterpriseCertEndDate() {
        return enterpriseCertEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_END_DATE
     *
     * @param enterpriseCertEndDate the value for TB_CSM_CORPORATION.ENTERPRISE_CERT_END_DATE
     *
     * @mbg.generated
     */
    public void setEnterpriseCertEndDate(Date enterpriseCertEndDate) {
        this.enterpriseCertEndDate = enterpriseCertEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_NUM
     *
     * @return the value of TB_CSM_CORPORATION.ENTERPRISE_CERT_NUM
     *
     * @mbg.generated
     */
    public String getEnterpriseCertNum() {
        return enterpriseCertNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ENTERPRISE_CERT_NUM
     *
     * @param enterpriseCertNum the value for TB_CSM_CORPORATION.ENTERPRISE_CERT_NUM
     *
     * @mbg.generated
     */
    public void setEnterpriseCertNum(String enterpriseCertNum) {
        this.enterpriseCertNum = enterpriseCertNum == null ? null : enterpriseCertNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.UNIFY_SOCIETY_CREDIT_NUM
     *
     * @return the value of TB_CSM_CORPORATION.UNIFY_SOCIETY_CREDIT_NUM
     *
     * @mbg.generated
     */
    public String getUnifySocietyCreditNum() {
        return unifySocietyCreditNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.UNIFY_SOCIETY_CREDIT_NUM
     *
     * @param unifySocietyCreditNum the value for TB_CSM_CORPORATION.UNIFY_SOCIETY_CREDIT_NUM
     *
     * @mbg.generated
     */
    public void setUnifySocietyCreditNum(String unifySocietyCreditNum) {
        this.unifySocietyCreditNum = unifySocietyCreditNum == null ? null : unifySocietyCreditNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.SINGLE_LP_CUST_IND
     *
     * @return the value of TB_CSM_CORPORATION.SINGLE_LP_CUST_IND
     *
     * @mbg.generated
     */
    public String getSingleLpCustInd() {
        return singleLpCustInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.SINGLE_LP_CUST_IND
     *
     * @param singleLpCustInd the value for TB_CSM_CORPORATION.SINGLE_LP_CUST_IND
     *
     * @mbg.generated
     */
    public void setSingleLpCustInd(String singleLpCustInd) {
        this.singleLpCustInd = singleLpCustInd == null ? null : singleLpCustInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.STOP_CORP_IND
     *
     * @return the value of TB_CSM_CORPORATION.STOP_CORP_IND
     *
     * @mbg.generated
     */
    public String getStopCorpInd() {
        return stopCorpInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.STOP_CORP_IND
     *
     * @param stopCorpInd the value for TB_CSM_CORPORATION.STOP_CORP_IND
     *
     * @mbg.generated
     */
    public void setStopCorpInd(String stopCorpInd) {
        this.stopCorpInd = stopCorpInd == null ? null : stopCorpInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_CONTRY
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_CONTRY
     *
     * @mbg.generated
     */
    public String getLegalContry() {
        return legalContry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_CONTRY
     *
     * @param legalContry the value for TB_CSM_CORPORATION.LEGAL_CONTRY
     *
     * @mbg.generated
     */
    public void setLegalContry(String legalContry) {
        this.legalContry = legalContry == null ? null : legalContry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.BANK_SCALE_IDENTIFY
     *
     * @return the value of TB_CSM_CORPORATION.BANK_SCALE_IDENTIFY
     *
     * @mbg.generated
     */
    public String getBankScaleIdentify() {
        return bankScaleIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.BANK_SCALE_IDENTIFY
     *
     * @param bankScaleIdentify the value for TB_CSM_CORPORATION.BANK_SCALE_IDENTIFY
     *
     * @mbg.generated
     */
    public void setBankScaleIdentify(String bankScaleIdentify) {
        this.bankScaleIdentify = bankScaleIdentify == null ? null : bankScaleIdentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_PHONE_NUMBER
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_PHONE_NUMBER
     *
     * @mbg.generated
     */
    public String getLegalPhoneNumber() {
        return legalPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_PHONE_NUMBER
     *
     * @param legalPhoneNumber the value for TB_CSM_CORPORATION.LEGAL_PHONE_NUMBER
     *
     * @mbg.generated
     */
    public void setLegalPhoneNumber(String legalPhoneNumber) {
        this.legalPhoneNumber = legalPhoneNumber == null ? null : legalPhoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_REGIST_DATE
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_REGIST_DATE
     *
     * @mbg.generated
     */
    public Date getLegalRegistDate() {
        return legalRegistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_REGIST_DATE
     *
     * @param legalRegistDate the value for TB_CSM_CORPORATION.LEGAL_REGIST_DATE
     *
     * @mbg.generated
     */
    public void setLegalRegistDate(Date legalRegistDate) {
        this.legalRegistDate = legalRegistDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LEGAL_CONTRY_SIGN
     *
     * @return the value of TB_CSM_CORPORATION.LEGAL_CONTRY_SIGN
     *
     * @mbg.generated
     */
    public String getLegalContrySign() {
        return legalContrySign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LEGAL_CONTRY_SIGN
     *
     * @param legalContrySign the value for TB_CSM_CORPORATION.LEGAL_CONTRY_SIGN
     *
     * @mbg.generated
     */
    public void setLegalContrySign(String legalContrySign) {
        this.legalContrySign = legalContrySign == null ? null : legalContrySign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_TECHNIC
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_TECHNIC
     *
     * @mbg.generated
     */
    public String getWhetherTechnic() {
        return whetherTechnic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_TECHNIC
     *
     * @param whetherTechnic the value for TB_CSM_CORPORATION.WHETHER_TECHNIC
     *
     * @mbg.generated
     */
    public void setWhetherTechnic(String whetherTechnic) {
        this.whetherTechnic = whetherTechnic == null ? null : whetherTechnic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_GREEN_GROUP
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_GREEN_GROUP
     *
     * @mbg.generated
     */
    public String getWhetherGreenGroup() {
        return whetherGreenGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_GREEN_GROUP
     *
     * @param whetherGreenGroup the value for TB_CSM_CORPORATION.WHETHER_GREEN_GROUP
     *
     * @mbg.generated
     */
    public void setWhetherGreenGroup(String whetherGreenGroup) {
        this.whetherGreenGroup = whetherGreenGroup == null ? null : whetherGreenGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_JMRH
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_JMRH
     *
     * @mbg.generated
     */
    public String getWhetherJmrh() {
        return whetherJmrh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_JMRH
     *
     * @param whetherJmrh the value for TB_CSM_CORPORATION.WHETHER_JMRH
     *
     * @mbg.generated
     */
    public void setWhetherJmrh(String whetherJmrh) {
        this.whetherJmrh = whetherJmrh == null ? null : whetherJmrh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_ARG_RELATED
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_ARG_RELATED
     *
     * @mbg.generated
     */
    public String getWhetherArgRelated() {
        return whetherArgRelated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_ARG_RELATED
     *
     * @param whetherArgRelated the value for TB_CSM_CORPORATION.WHETHER_ARG_RELATED
     *
     * @mbg.generated
     */
    public void setWhetherArgRelated(String whetherArgRelated) {
        this.whetherArgRelated = whetherArgRelated == null ? null : whetherArgRelated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_OPEN_ACCT
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_OPEN_ACCT
     *
     * @mbg.generated
     */
    public String getWhetherOpenAcct() {
        return whetherOpenAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_OPEN_ACCT
     *
     * @param whetherOpenAcct the value for TB_CSM_CORPORATION.WHETHER_OPEN_ACCT
     *
     * @mbg.generated
     */
    public void setWhetherOpenAcct(String whetherOpenAcct) {
        this.whetherOpenAcct = whetherOpenAcct == null ? null : whetherOpenAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.WHETHER_POVERTY_ADD
     *
     * @return the value of TB_CSM_CORPORATION.WHETHER_POVERTY_ADD
     *
     * @mbg.generated
     */
    public String getWhetherPovertyAdd() {
        return whetherPovertyAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.WHETHER_POVERTY_ADD
     *
     * @param whetherPovertyAdd the value for TB_CSM_CORPORATION.WHETHER_POVERTY_ADD
     *
     * @mbg.generated
     */
    public void setWhetherPovertyAdd(String whetherPovertyAdd) {
        this.whetherPovertyAdd = whetherPovertyAdd == null ? null : whetherPovertyAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.AREA
     *
     * @return the value of TB_CSM_CORPORATION.AREA
     *
     * @mbg.generated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.AREA
     *
     * @param area the value for TB_CSM_CORPORATION.AREA
     *
     * @mbg.generated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.OWNER
     *
     * @return the value of TB_CSM_CORPORATION.OWNER
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.OWNER
     *
     * @param owner the value for TB_CSM_CORPORATION.OWNER
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.NATIONAL_ECONOMY_TYPE
     *
     * @return the value of TB_CSM_CORPORATION.NATIONAL_ECONOMY_TYPE
     *
     * @mbg.generated
     */
    public String getNationalEconomyType() {
        return nationalEconomyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.NATIONAL_ECONOMY_TYPE
     *
     * @param nationalEconomyType the value for TB_CSM_CORPORATION.NATIONAL_ECONOMY_TYPE
     *
     * @mbg.generated
     */
    public void setNationalEconomyType(String nationalEconomyType) {
        this.nationalEconomyType = nationalEconomyType == null ? null : nationalEconomyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.CHAIN_SIGN
     *
     * @return the value of TB_CSM_CORPORATION.CHAIN_SIGN
     *
     * @mbg.generated
     */
    public String getChainSign() {
        return chainSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.CHAIN_SIGN
     *
     * @param chainSign the value for TB_CSM_CORPORATION.CHAIN_SIGN
     *
     * @mbg.generated
     */
    public void setChainSign(String chainSign) {
        this.chainSign = chainSign == null ? null : chainSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.MAIN_CUST_TYPE_CD
     *
     * @return the value of TB_CSM_CORPORATION.MAIN_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public String getMainCustTypeCd() {
        return mainCustTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.MAIN_CUST_TYPE_CD
     *
     * @param mainCustTypeCd the value for TB_CSM_CORPORATION.MAIN_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public void setMainCustTypeCd(String mainCustTypeCd) {
        this.mainCustTypeCd = mainCustTypeCd == null ? null : mainCustTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.ORG_STATUS
     *
     * @return the value of TB_CSM_CORPORATION.ORG_STATUS
     *
     * @mbg.generated
     */
    public String getOrgStatus() {
        return orgStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.ORG_STATUS
     *
     * @param orgStatus the value for TB_CSM_CORPORATION.ORG_STATUS
     *
     * @mbg.generated
     */
    public void setOrgStatus(String orgStatus) {
        this.orgStatus = orgStatus == null ? null : orgStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.IF_CSY
     *
     * @return the value of TB_CSM_CORPORATION.IF_CSY
     *
     * @mbg.generated
     */
    public String getIfCsy() {
        return ifCsy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.IF_CSY
     *
     * @param ifCsy the value for TB_CSM_CORPORATION.IF_CSY
     *
     * @mbg.generated
     */
    public void setIfCsy(String ifCsy) {
        this.ifCsy = ifCsy == null ? null : ifCsy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_CSM_CORPORATION.LOAN_TURN
     *
     * @return the value of TB_CSM_CORPORATION.LOAN_TURN
     *
     * @mbg.generated
     */
    public String getLoanTurn() {
        return loanTurn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_CSM_CORPORATION.LOAN_TURN
     *
     * @param loanTurn the value for TB_CSM_CORPORATION.LOAN_TURN
     *
     * @mbg.generated
     */
    public void setLoanTurn(String loanTurn) {
        this.loanTurn = loanTurn == null ? null : loanTurn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        tb_csm_corporation other = (tb_csm_corporation) that;
        return (this.getPartyId() == null ? other.getPartyId() == null : this.getPartyId().equals(other.getPartyId()))
            && (this.getCorpCustomerTypeCd() == null ? other.getCorpCustomerTypeCd() == null : this.getCorpCustomerTypeCd().equals(other.getCorpCustomerTypeCd()))
            && (this.getEnglishName() == null ? other.getEnglishName() == null : this.getEnglishName().equals(other.getEnglishName()))
            && (this.getEconomicSectorCode() == null ? other.getEconomicSectorCode() == null : this.getEconomicSectorCode().equals(other.getEconomicSectorCode()))
            && (this.getIndustrialTypeCd() == null ? other.getIndustrialTypeCd() == null : this.getIndustrialTypeCd().equals(other.getIndustrialTypeCd()))
            && (this.getListingCorporation() == null ? other.getListingCorporation() == null : this.getListingCorporation().equals(other.getListingCorporation()))
            && (this.getRegisterAssets() == null ? other.getRegisterAssets() == null : this.getRegisterAssets().equals(other.getRegisterAssets()))
            && (this.getRegisterAssetsCurrencyCd() == null ? other.getRegisterAssetsCurrencyCd() == null : this.getRegisterAssetsCurrencyCd().equals(other.getRegisterAssetsCurrencyCd()))
            && (this.getEmployeesNumber() == null ? other.getEmployeesNumber() == null : this.getEmployeesNumber().equals(other.getEmployeesNumber()))
            && (this.getGovernmentTentNo() == null ? other.getGovernmentTentNo() == null : this.getGovernmentTentNo().equals(other.getGovernmentTentNo()))
            && (this.getCreditRelationshipTime() == null ? other.getCreditRelationshipTime() == null : this.getCreditRelationshipTime().equals(other.getCreditRelationshipTime()))
            && (this.getRegisterDate() == null ? other.getRegisterDate() == null : this.getRegisterDate().equals(other.getRegisterDate()))
            && (this.getLegalCertificateNo() == null ? other.getLegalCertificateNo() == null : this.getLegalCertificateNo().equals(other.getLegalCertificateNo()))
            && (this.getLegalCertificateEndDate() == null ? other.getLegalCertificateEndDate() == null : this.getLegalCertificateEndDate().equals(other.getLegalCertificateEndDate()))
            && (this.getRegistrationType() == null ? other.getRegistrationType() == null : this.getRegistrationType().equals(other.getRegistrationType()))
            && (this.getUpdateUserNum() == null ? other.getUpdateUserNum() == null : this.getUpdateUserNum().equals(other.getUpdateUserNum()))
            && (this.getUpdateOrgNum() == null ? other.getUpdateOrgNum() == null : this.getUpdateOrgNum().equals(other.getUpdateOrgNum()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getAreaType() == null ? other.getAreaType() == null : this.getAreaType().equals(other.getAreaType()))
            && (this.getContryRegionCd() == null ? other.getContryRegionCd() == null : this.getContryRegionCd().equals(other.getContryRegionCd()))
            && (this.getLegalName() == null ? other.getLegalName() == null : this.getLegalName().equals(other.getLegalName()))
            && (this.getLegalCertType() == null ? other.getLegalCertType() == null : this.getLegalCertType().equals(other.getLegalCertType()))
            && (this.getRegistrCd() == null ? other.getRegistrCd() == null : this.getRegistrCd().equals(other.getRegistrCd()))
            && (this.getRegisterEndDate() == null ? other.getRegisterEndDate() == null : this.getRegisterEndDate().equals(other.getRegisterEndDate()))
            && (this.getBusinessScope() == null ? other.getBusinessScope() == null : this.getBusinessScope().equals(other.getBusinessScope()))
            && (this.getOrgRegisterCd() == null ? other.getOrgRegisterCd() == null : this.getOrgRegisterCd().equals(other.getOrgRegisterCd()))
            && (this.getOrgRegisterEndDate() == null ? other.getOrgRegisterEndDate() == null : this.getOrgRegisterEndDate().equals(other.getOrgRegisterEndDate()))
            && (this.getMiddelCode() == null ? other.getMiddelCode() == null : this.getMiddelCode().equals(other.getMiddelCode()))
            && (this.getOrgCreditCode() == null ? other.getOrgCreditCode() == null : this.getOrgCreditCode().equals(other.getOrgCreditCode()))
            && (this.getNationalTaxNo() == null ? other.getNationalTaxNo() == null : this.getNationalTaxNo().equals(other.getNationalTaxNo()))
            && (this.getIndustrialTypeBigCd() == null ? other.getIndustrialTypeBigCd() == null : this.getIndustrialTypeBigCd().equals(other.getIndustrialTypeBigCd()))
            && (this.getIndustrialTypeMidCd() == null ? other.getIndustrialTypeMidCd() == null : this.getIndustrialTypeMidCd().equals(other.getIndustrialTypeMidCd()))
            && (this.getIndustrialTypeSamllCd() == null ? other.getIndustrialTypeSamllCd() == null : this.getIndustrialTypeSamllCd().equals(other.getIndustrialTypeSamllCd()))
            && (this.getEnterpriseScaleGx() == null ? other.getEnterpriseScaleGx() == null : this.getEnterpriseScaleGx().equals(other.getEnterpriseScaleGx()))
            && (this.getCountBoreEnterScale() == null ? other.getCountBoreEnterScale() == null : this.getCountBoreEnterScale().equals(other.getCountBoreEnterScale()))
            && (this.getIsGroupCust() == null ? other.getIsGroupCust() == null : this.getIsGroupCust().equals(other.getIsGroupCust()))
            && (this.getAttachGroupName() == null ? other.getAttachGroupName() == null : this.getAttachGroupName().equals(other.getAttachGroupName()))
            && (this.getWhetherImpExp() == null ? other.getWhetherImpExp() == null : this.getWhetherImpExp().equals(other.getWhetherImpExp()))
            && (this.getStockholderOfBank() == null ? other.getStockholderOfBank() == null : this.getStockholderOfBank().equals(other.getStockholderOfBank()))
            && (this.getJointGuarantee() == null ? other.getJointGuarantee() == null : this.getJointGuarantee().equals(other.getJointGuarantee()))
            && (this.getFamilyEnterprise() == null ? other.getFamilyEnterprise() == null : this.getFamilyEnterprise().equals(other.getFamilyEnterprise()))
            && (this.getWhetherGovernmentFinanceCor() == null ? other.getWhetherGovernmentFinanceCor() == null : this.getWhetherGovernmentFinanceCor().equals(other.getWhetherGovernmentFinanceCor()))
            && (this.getCountrysideEnterprise() == null ? other.getCountrysideEnterprise() == null : this.getCountrysideEnterprise().equals(other.getCountrysideEnterprise()))
            && (this.getWhetherBlackList() == null ? other.getWhetherBlackList() == null : this.getWhetherBlackList().equals(other.getWhetherBlackList()))
            && (this.getFocusCustomer() == null ? other.getFocusCustomer() == null : this.getFocusCustomer().equals(other.getFocusCustomer()))
            && (this.getIsRealEstateDev() == null ? other.getIsRealEstateDev() == null : this.getIsRealEstateDev().equals(other.getIsRealEstateDev()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()))
            && (this.getFundSrc() == null ? other.getFundSrc() == null : this.getFundSrc().equals(other.getFundSrc()))
            && (this.getOpenFund() == null ? other.getOpenFund() == null : this.getOpenFund().equals(other.getOpenFund()))
            && (this.getIsBasebankRelaCust() == null ? other.getIsBasebankRelaCust() == null : this.getIsBasebankRelaCust().equals(other.getIsBasebankRelaCust()))
            && (this.getThirdCustTypeCd() == null ? other.getThirdCustTypeCd() == null : this.getThirdCustTypeCd().equals(other.getThirdCustTypeCd()))
            && (this.getIsThirdCust() == null ? other.getIsThirdCust() == null : this.getIsThirdCust().equals(other.getIsThirdCust()))
            && (this.getEnterpriseCertEndDate() == null ? other.getEnterpriseCertEndDate() == null : this.getEnterpriseCertEndDate().equals(other.getEnterpriseCertEndDate()))
            && (this.getEnterpriseCertNum() == null ? other.getEnterpriseCertNum() == null : this.getEnterpriseCertNum().equals(other.getEnterpriseCertNum()))
            && (this.getUnifySocietyCreditNum() == null ? other.getUnifySocietyCreditNum() == null : this.getUnifySocietyCreditNum().equals(other.getUnifySocietyCreditNum()))
            && (this.getSingleLpCustInd() == null ? other.getSingleLpCustInd() == null : this.getSingleLpCustInd().equals(other.getSingleLpCustInd()))
            && (this.getStopCorpInd() == null ? other.getStopCorpInd() == null : this.getStopCorpInd().equals(other.getStopCorpInd()))
            && (this.getLegalContry() == null ? other.getLegalContry() == null : this.getLegalContry().equals(other.getLegalContry()))
            && (this.getBankScaleIdentify() == null ? other.getBankScaleIdentify() == null : this.getBankScaleIdentify().equals(other.getBankScaleIdentify()))
            && (this.getLegalPhoneNumber() == null ? other.getLegalPhoneNumber() == null : this.getLegalPhoneNumber().equals(other.getLegalPhoneNumber()))
            && (this.getLegalRegistDate() == null ? other.getLegalRegistDate() == null : this.getLegalRegistDate().equals(other.getLegalRegistDate()))
            && (this.getLegalContrySign() == null ? other.getLegalContrySign() == null : this.getLegalContrySign().equals(other.getLegalContrySign()))
            && (this.getWhetherTechnic() == null ? other.getWhetherTechnic() == null : this.getWhetherTechnic().equals(other.getWhetherTechnic()))
            && (this.getWhetherGreenGroup() == null ? other.getWhetherGreenGroup() == null : this.getWhetherGreenGroup().equals(other.getWhetherGreenGroup()))
            && (this.getWhetherJmrh() == null ? other.getWhetherJmrh() == null : this.getWhetherJmrh().equals(other.getWhetherJmrh()))
            && (this.getWhetherArgRelated() == null ? other.getWhetherArgRelated() == null : this.getWhetherArgRelated().equals(other.getWhetherArgRelated()))
            && (this.getWhetherOpenAcct() == null ? other.getWhetherOpenAcct() == null : this.getWhetherOpenAcct().equals(other.getWhetherOpenAcct()))
            && (this.getWhetherPovertyAdd() == null ? other.getWhetherPovertyAdd() == null : this.getWhetherPovertyAdd().equals(other.getWhetherPovertyAdd()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getOwner() == null ? other.getOwner() == null : this.getOwner().equals(other.getOwner()))
            && (this.getNationalEconomyType() == null ? other.getNationalEconomyType() == null : this.getNationalEconomyType().equals(other.getNationalEconomyType()))
            && (this.getChainSign() == null ? other.getChainSign() == null : this.getChainSign().equals(other.getChainSign()))
            && (this.getMainCustTypeCd() == null ? other.getMainCustTypeCd() == null : this.getMainCustTypeCd().equals(other.getMainCustTypeCd()))
            && (this.getOrgStatus() == null ? other.getOrgStatus() == null : this.getOrgStatus().equals(other.getOrgStatus()))
            && (this.getIfCsy() == null ? other.getIfCsy() == null : this.getIfCsy().equals(other.getIfCsy()))
            && (this.getLoanTurn() == null ? other.getLoanTurn() == null : this.getLoanTurn().equals(other.getLoanTurn()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getPartyId() == null) ? 0 : getPartyId().hashCode());
        result = prime * result + ((getCorpCustomerTypeCd() == null) ? 0 : getCorpCustomerTypeCd().hashCode());
        result = prime * result + ((getEnglishName() == null) ? 0 : getEnglishName().hashCode());
        result = prime * result + ((getEconomicSectorCode() == null) ? 0 : getEconomicSectorCode().hashCode());
        result = prime * result + ((getIndustrialTypeCd() == null) ? 0 : getIndustrialTypeCd().hashCode());
        result = prime * result + ((getListingCorporation() == null) ? 0 : getListingCorporation().hashCode());
        result = prime * result + ((getRegisterAssets() == null) ? 0 : getRegisterAssets().hashCode());
        result = prime * result + ((getRegisterAssetsCurrencyCd() == null) ? 0 : getRegisterAssetsCurrencyCd().hashCode());
        result = prime * result + ((getEmployeesNumber() == null) ? 0 : getEmployeesNumber().hashCode());
        result = prime * result + ((getGovernmentTentNo() == null) ? 0 : getGovernmentTentNo().hashCode());
        result = prime * result + ((getCreditRelationshipTime() == null) ? 0 : getCreditRelationshipTime().hashCode());
        result = prime * result + ((getRegisterDate() == null) ? 0 : getRegisterDate().hashCode());
        result = prime * result + ((getLegalCertificateNo() == null) ? 0 : getLegalCertificateNo().hashCode());
        result = prime * result + ((getLegalCertificateEndDate() == null) ? 0 : getLegalCertificateEndDate().hashCode());
        result = prime * result + ((getRegistrationType() == null) ? 0 : getRegistrationType().hashCode());
        result = prime * result + ((getUpdateUserNum() == null) ? 0 : getUpdateUserNum().hashCode());
        result = prime * result + ((getUpdateOrgNum() == null) ? 0 : getUpdateOrgNum().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getAreaType() == null) ? 0 : getAreaType().hashCode());
        result = prime * result + ((getContryRegionCd() == null) ? 0 : getContryRegionCd().hashCode());
        result = prime * result + ((getLegalName() == null) ? 0 : getLegalName().hashCode());
        result = prime * result + ((getLegalCertType() == null) ? 0 : getLegalCertType().hashCode());
        result = prime * result + ((getRegistrCd() == null) ? 0 : getRegistrCd().hashCode());
        result = prime * result + ((getRegisterEndDate() == null) ? 0 : getRegisterEndDate().hashCode());
        result = prime * result + ((getBusinessScope() == null) ? 0 : getBusinessScope().hashCode());
        result = prime * result + ((getOrgRegisterCd() == null) ? 0 : getOrgRegisterCd().hashCode());
        result = prime * result + ((getOrgRegisterEndDate() == null) ? 0 : getOrgRegisterEndDate().hashCode());
        result = prime * result + ((getMiddelCode() == null) ? 0 : getMiddelCode().hashCode());
        result = prime * result + ((getOrgCreditCode() == null) ? 0 : getOrgCreditCode().hashCode());
        result = prime * result + ((getNationalTaxNo() == null) ? 0 : getNationalTaxNo().hashCode());
        result = prime * result + ((getIndustrialTypeBigCd() == null) ? 0 : getIndustrialTypeBigCd().hashCode());
        result = prime * result + ((getIndustrialTypeMidCd() == null) ? 0 : getIndustrialTypeMidCd().hashCode());
        result = prime * result + ((getIndustrialTypeSamllCd() == null) ? 0 : getIndustrialTypeSamllCd().hashCode());
        result = prime * result + ((getEnterpriseScaleGx() == null) ? 0 : getEnterpriseScaleGx().hashCode());
        result = prime * result + ((getCountBoreEnterScale() == null) ? 0 : getCountBoreEnterScale().hashCode());
        result = prime * result + ((getIsGroupCust() == null) ? 0 : getIsGroupCust().hashCode());
        result = prime * result + ((getAttachGroupName() == null) ? 0 : getAttachGroupName().hashCode());
        result = prime * result + ((getWhetherImpExp() == null) ? 0 : getWhetherImpExp().hashCode());
        result = prime * result + ((getStockholderOfBank() == null) ? 0 : getStockholderOfBank().hashCode());
        result = prime * result + ((getJointGuarantee() == null) ? 0 : getJointGuarantee().hashCode());
        result = prime * result + ((getFamilyEnterprise() == null) ? 0 : getFamilyEnterprise().hashCode());
        result = prime * result + ((getWhetherGovernmentFinanceCor() == null) ? 0 : getWhetherGovernmentFinanceCor().hashCode());
        result = prime * result + ((getCountrysideEnterprise() == null) ? 0 : getCountrysideEnterprise().hashCode());
        result = prime * result + ((getWhetherBlackList() == null) ? 0 : getWhetherBlackList().hashCode());
        result = prime * result + ((getFocusCustomer() == null) ? 0 : getFocusCustomer().hashCode());
        result = prime * result + ((getIsRealEstateDev() == null) ? 0 : getIsRealEstateDev().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        result = prime * result + ((getFundSrc() == null) ? 0 : getFundSrc().hashCode());
        result = prime * result + ((getOpenFund() == null) ? 0 : getOpenFund().hashCode());
        result = prime * result + ((getIsBasebankRelaCust() == null) ? 0 : getIsBasebankRelaCust().hashCode());
        result = prime * result + ((getThirdCustTypeCd() == null) ? 0 : getThirdCustTypeCd().hashCode());
        result = prime * result + ((getIsThirdCust() == null) ? 0 : getIsThirdCust().hashCode());
        result = prime * result + ((getEnterpriseCertEndDate() == null) ? 0 : getEnterpriseCertEndDate().hashCode());
        result = prime * result + ((getEnterpriseCertNum() == null) ? 0 : getEnterpriseCertNum().hashCode());
        result = prime * result + ((getUnifySocietyCreditNum() == null) ? 0 : getUnifySocietyCreditNum().hashCode());
        result = prime * result + ((getSingleLpCustInd() == null) ? 0 : getSingleLpCustInd().hashCode());
        result = prime * result + ((getStopCorpInd() == null) ? 0 : getStopCorpInd().hashCode());
        result = prime * result + ((getLegalContry() == null) ? 0 : getLegalContry().hashCode());
        result = prime * result + ((getBankScaleIdentify() == null) ? 0 : getBankScaleIdentify().hashCode());
        result = prime * result + ((getLegalPhoneNumber() == null) ? 0 : getLegalPhoneNumber().hashCode());
        result = prime * result + ((getLegalRegistDate() == null) ? 0 : getLegalRegistDate().hashCode());
        result = prime * result + ((getLegalContrySign() == null) ? 0 : getLegalContrySign().hashCode());
        result = prime * result + ((getWhetherTechnic() == null) ? 0 : getWhetherTechnic().hashCode());
        result = prime * result + ((getWhetherGreenGroup() == null) ? 0 : getWhetherGreenGroup().hashCode());
        result = prime * result + ((getWhetherJmrh() == null) ? 0 : getWhetherJmrh().hashCode());
        result = prime * result + ((getWhetherArgRelated() == null) ? 0 : getWhetherArgRelated().hashCode());
        result = prime * result + ((getWhetherOpenAcct() == null) ? 0 : getWhetherOpenAcct().hashCode());
        result = prime * result + ((getWhetherPovertyAdd() == null) ? 0 : getWhetherPovertyAdd().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getOwner() == null) ? 0 : getOwner().hashCode());
        result = prime * result + ((getNationalEconomyType() == null) ? 0 : getNationalEconomyType().hashCode());
        result = prime * result + ((getChainSign() == null) ? 0 : getChainSign().hashCode());
        result = prime * result + ((getMainCustTypeCd() == null) ? 0 : getMainCustTypeCd().hashCode());
        result = prime * result + ((getOrgStatus() == null) ? 0 : getOrgStatus().hashCode());
        result = prime * result + ((getIfCsy() == null) ? 0 : getIfCsy().hashCode());
        result = prime * result + ((getLoanTurn() == null) ? 0 : getLoanTurn().hashCode());
        return result;
    }
}