package com.cdgit.loan.csm.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.cdgit.loan.csm.bean.tb_csm_corporation;
import com.cdgit.loan.csm.bean.tb_csm_corporationExample;

public interface tb_csm_corporationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    long countByExample(tb_csm_corporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int deleteByExample(tb_csm_corporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int insert(tb_csm_corporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int insertSelective(tb_csm_corporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    List<tb_csm_corporation> selectByExample(tb_csm_corporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    tb_csm_corporation selectByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") tb_csm_corporation record, @Param("example") tb_csm_corporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") tb_csm_corporation record, @Param("example") tb_csm_corporationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(tb_csm_corporation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_CSM_CORPORATION
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(tb_csm_corporation record);
}